### PR TITLE
bump version to 13-latest

### PR DESCRIPTION
**Pull request by chdsbd**
The AST changed between 10 and 13, so this would be a breaking change.

### CODE REVIEW

**Comment by autarch** [comment]
Hi Christopher,

Thanks for this PR.

This is an interesting case for semantic versioning. I'm wondering if it'd make sense to switch this crate to a system that mirrors the Pg version and `libpg_query` version that it's linking against. Of course, the `libpg_query` version doesn't _fit_ in semantic versioning, since it's currently `13-2.1.0`. Alternatively, we could use the relevant Pg version (13.2) and use the patchlevel to indicate something about this crate or the `libpg_query` version.

Do you have thoughts about this? @tdbgamer, if you have any ideas on this I'd love to get your input too!

Cheers,

Dave

**Comment by timbess** [comment]
Hmm I think generally in this scenario, most libraries I've seen tend to do their own semantic versioning independently and just throw a table in the README mapping versions of the wrapper lib to the underlying lib.

Overall I'm not super opinionated on how this is done. This is the sort of thing where I expect most consumers would understand they need to build an abstraction layer over this to protect themselves from changes made by postgresql anyways.

**Comment by autarch** [comment]
> Hmm I think generally in this scenario, most libraries I've seen tend to do their own semantic versioning independently and just throw a table in the README mapping versions of the wrapper lib to the underlying lib.
> 
> Overall I'm not super opinionated on how this is done. This is the sort of thing where I expect most consumers would understand they need to build an abstraction layer over this to protect themselves from changes made by postgresql anyways.

I think in this case it'd make sense to bump the version to `1.0.0` for this change, and then bump the major version whenever the associated Pg major version changes. And for any other releases we'd bump the minor or patchlevel versions and update the table in the `README.md` as needed if there's an associated Pg version bump.

**Comment by autarch** [comment]
> I think in this case it'd make sense to bump the version to `1.0.0` for this change, and then bump the major version whenever the associated Pg major version changes. And for any other releases we'd bump the minor or patchlevel versions and update the table in the `README.md` as needed if there's an associated Pg version bump.

Actually, I think I'll just make this version 0.2.0. Version 0 is unstable anyway, and I'm a bit leary of bumping this to 1.0.0 without knowing if it's actually stable.

**Comment by autarch** [comment]
Thanks for this! I merged it with some tweaks from the command line.

**Pull request closed without merging**
